const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const path = require('node:path');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync(process.argv[2] || path.join(__dirname,'../overlay/assets/emmet/emmet.js'),'utf8'),context);
const expand = context.CodeIDEEmmet.expand;
let count=0;
function run(text,syntax='html',extra={}) { return expand({text,syntax,start:text.length,end:text.length,indent:'  ',lang:'pl',...extra}); }
function test(name,fn) { try {fn();count++;} catch(e) {console.error(name);throw e;} }
function output(text,syntax,expected,extra) {const r=run(text,syntax,extra);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.text,expected);assert(r.selectionStart>=0 && r.selectionEnd<=r.text.length);return r;}
test('HTML children and numbering',()=>output('ul>li.item$*3','html','<ul>\n  <li class="item1"></li>\n  <li class="item2"></li>\n  <li class="item3"></li>\n</ul>'));
test('climb and siblings',()=>output('div>p^footer','html','<div>\n  <p></p>\n</div>\n<footer></footer>'));
test('grouping',()=>assert.equal((run('(header>nav)+footer').text.match(/<footer>/g)||[]).length,1));
test('text and custom attributes',()=>output('a[href=/]{Żółć}','html','<a href="/">Żółć</a>'));
test('HTML5 document',()=>{const r=run('!');assert(r.ok);assert(r.text.startsWith('<!DOCTYPE html>'));assert(r.text.includes('lang="pl"'));assert(!r.text.includes('${'));});
test('first editable field',()=>{const r=output('a','html','<a href=""></a>');assert.equal(r.selectionStart,9);assert.equal(r.selectionEnd,9);});
test('CSS margin',()=>output('m10-20','css','margin: 10px 20px;'));
test('CSS padding',()=>output('p16','css','padding: 16px;'));
test('CSS flex',()=>output('df','css','display: flex;'));
test('SCSS',()=>output('m10','scss','margin: 10px;'));
test('Sass',()=>output('m10','sass','margin: 10px'));
test('Stylus',()=>output('m10','stylus','margin 10px'));
test('CSS value',()=>output('margin: a','css','auto'));
test('JSX class',()=>output('div.card','jsx','<div className="card"></div>'));
test('TSX alias',()=>output('label','tsx','<label htmlFor=""></label>'));
test('XML self closing',()=>output('node/','xml','<node/>'));
test('implicit list parent',()=>output('<ul>\n  .item','html','<li class="item"></li>'));
test('inline style',()=>output('<div style="m10','html','margin: 10px;'));
test('style element',()=>output('<style>\n  m10','html','margin: 10px;'));
test('script blocked',()=>assert.equal(run('<script>\ndiv').error,'context'));
test('comment blocked',()=>assert.equal(run('<!--\ndiv').error,'context'));
test('ordinary attribute blocked',()=>assert.equal(run('<div title="div').error,'context'));
test('closed script',()=>output('<script>x</script>\ndiv','html','<div></div>'));
test('closed comment',()=>output('<!-- x -->\ndiv','html','<div></div>'));
test('indent and CRLF',()=>output('x\r\n\tul>li','html','<ul>\r\n\t  <li></li>\r\n\t</ul>'));
test('selected abbreviation preserves surrounding text',()=>{const r=output('before div after','html','<div></div>',{start:7,end:10});assert.equal(r.start,7);assert.equal(r.end,10);});
test('reverse selection',()=>output('div','html','<div></div>',{start:3,end:0}));
test('UTF16 prefix',()=>{const r=run('😀\ndiv');assert.equal(r.start,3);assert.equal(r.end,6);assert(r.ok);});
test('UTF16 text',()=>output('p{😀}','html','<p>😀</p>'));
test('empty document',()=>assert.equal(run('').ok,false));
test('start of file',()=>assert.equal(run('div','html',{start:0,end:0}).ok,false));
test('unsupported syntax',()=>assert.equal(run('div','python').error,'syntax'));
test('invalid range',()=>assert.equal(run('div','html',{start:-1,end:3}).error,'selection'));
test('malformed expression',()=>assert.equal(run('div)','html',{start:0,end:4}).ok,false));
test('repeat budget',()=>assert.equal(run('li*1000000').error,'size'));
test('document budget',()=>assert.equal(run('a'.repeat(524289)).error,'size'));
test('abbr budget',()=>assert.equal(run('a'.repeat(4097)).error,'size'));
console.log(`${count} Emmet regression cases passed`);
