package com.code.ide.compat;
import android.app.*;import android.content.*;import android.graphics.Rect;import android.os.*;import android.text.*;import android.view.*;import android.view.inputmethod.*;import android.webkit.*;import android.widget.*;import org.json.*;import java.util.*;
public final class EditorAssist implements TextWatcher {
 private static final Map<EditText,EditorAssist> sessions=new HashMap<EditText,EditorAssist>();
 final Activity activity;final EditText editor;final Handler handler=new Handler();WebView engine;boolean ready,closed,busy;int generation;PopupWindow popup;String snapshot;int caret;
 final Runnable pending=new Runnable(){public void run(){request();}};
 EditorAssist(Activity a,EditText e){activity=a;editor=e;}
 public static void start(Activity a,EditText e){stop(a);if(e==null)return;EditorAssist x=new EditorAssist(a,e);sessions.put(e,x);e.addTextChangedListener(x);}
 public static void stop(Activity a){for(EditorAssist x:new ArrayList<EditorAssist>(sessions.values()))if(x.activity==a){x.closed=true;x.handler.removeCallbacksAndMessages(null);x.hide();x.editor.removeTextChangedListener(x);sessions.remove(x.editor);if(x.engine!=null)x.engine.destroy();}}
 public static void dismiss(Activity a){for(EditorAssist x:sessions.values())if(x.activity==a){x.generation++;x.handler.removeCallbacks(x.pending);x.hide();}}
 static Activity host(EditText e){Context c=e.getContext();while(c instanceof ContextWrapper && !(c instanceof Activity)){Context next=((ContextWrapper)c).getBaseContext();if(next==c)break;c=next;}return c instanceof Activity?(Activity)c:null;}
 static String indent(EditText e){try{String s=(String)host(e).getClass().getMethod("getEmmetIndent").invoke(host(e));return s==null?"    ":s;}catch(Exception ex){return "    ";}}
 static String syntax(EditText e){try{return (String)host(e).getClass().getMethod("getEmmetSyntaxName").invoke(host(e));}catch(Exception ex){return "text";}}
 public static void selection(EditText e){EditorAssist x=sessions.get(e);if(x!=null){x.generation++;x.hide();}}
 static boolean automatic(EditText e){try{return (Boolean)host(e).getClass().getMethod("compatAutomaticEdit").invoke(host(e));}catch(Exception ex){return true;}}
 static boolean enabled(EditText e,String key){return e.getContext().getSharedPreferences("emmet",0).getBoolean(key,true);}
 static boolean apply(EditText e,PairRules.Edit edit){if(edit==null)return false;e.beginBatchEdit();try{e.getText().replace(edit.start,edit.end,edit.text);e.setSelection(edit.start+edit.from,edit.start+edit.to);}finally{e.endBatchEdit();}return true;}
 public static boolean type(EditText e,CharSequence value){if(e==null||value==null||value.length()!=1||!enabled(e,"pairs")||!e.isEnabled()||e.length()>512*1024)return false;int a=e.getSelectionStart(),b=e.getSelectionEnd();return apply(e,PairRules.type(e.getText().toString(),Math.min(a,b),Math.max(a,b),value.charAt(0),syntax(e)));}
 static boolean delete(EditText e){return enabled(e,"pairs")&&e.getSelectionStart()==e.getSelectionEnd()&&apply(e,PairRules.backspace(e.getText().toString(),e.getSelectionStart()));}
 public static boolean key(EditText e,KeyEvent event){if(event.getAction()!=KeyEvent.ACTION_DOWN||event.isCtrlPressed()||event.isAltPressed())return false;if(event.getKeyCode()==KeyEvent.KEYCODE_DEL)return delete(e);int c=event.getUnicodeChar();return c>0&&c<65536&&type(e,String.valueOf((char)c));}
 public static InputConnection wrap(final EditText e,InputConnection base){if(base==null)return null;return new InputConnectionWrapper(base,false){
  public boolean commitText(CharSequence s,int cursor){if(cursor==1 && BaseInputConnection.getComposingSpanStart(e.getText())<0 && type(e,s))return true;return super.commitText(s,cursor);}
  public boolean finishComposingText(){boolean ok=super.finishComposingText();EditorAssist x=sessions.get(e);if(x!=null&&enabled(e,"suggestions")){x.handler.removeCallbacks(x.pending);x.handler.postDelayed(x.pending,350);}return ok;}
  public boolean deleteSurroundingText(int before,int after){if(before==1&&after==0&&BaseInputConnection.getComposingSpanStart(e.getText())<0&&delete(e))return true;return super.deleteSurroundingText(before,after);}
 };}
 public void beforeTextChanged(CharSequence s,int st,int count,int after){}
 public void onTextChanged(CharSequence s,int st,int before,int count){generation++;handler.removeCallbacks(pending);hide();if(!busy&&!closed&&!automatic(editor)&&count>0&&count<130&&enabled(editor,"suggestions"))handler.postDelayed(pending,350);}
 public void afterTextChanged(Editable e){}
 void hide(){if(popup!=null){popup.dismiss();popup=null;}}
 void request(){if(closed||activity.isFinishing()||!editor.hasFocus()||editor.getSelectionStart()!=editor.getSelectionEnd()||editor.length()>512*1024||BaseInputConnection.getComposingSpanStart(editor.getText())>=0)return;
  if(engine==null){try{engine=new WebView(activity);WebSettings s=engine.getSettings();s.setJavaScriptEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setAllowFileAccessFromFileURLs(false);s.setAllowUniversalAccessFromFileURLs(false);s.setBlockNetworkLoads(true);s.setBlockNetworkImage(true);engine.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,String u){return true;}public void onPageFinished(WebView w,String u){ready=true;request();}});engine.loadDataWithBaseURL("https://emmet.invalid/",EmmetBridge.page(activity),"text/html","UTF-8",null);}catch(Exception ex){hide();}return;}
  if(!ready)return;final int token=generation;final String text=editor.getText().toString();final int pos=editor.getSelectionStart();
  try{JSONObject q=new JSONObject();q.put("text",text);q.put("start",pos);q.put("end",pos);q.put("syntax",syntax(editor));q.put("indent",indent(editor));q.put("snippets",EmmetSnippets.get(activity));String json=q.toString().replace("\u2028","\\u2028").replace("\u2029","\\u2029");engine.evaluateJavascript("CodeIDEEmmet.suggest("+json+")",new ValueCallback<String>(){public void onReceiveValue(String raw){if(closed||token!=generation||pos!=editor.getSelectionStart()||pos!=editor.getSelectionEnd()||!text.equals(editor.getText().toString()))return;try{show(new JSONArray(raw),text,pos);}catch(Exception ex){hide();}}});}catch(Exception ex){hide();}
 }
 int dp(int n){return (int)(activity.getResources().getDisplayMetrics().density*n);}
 void show(JSONArray rows,final String text,final int pos)throws Exception{hide();if(rows.length()==0)return;LinearLayout list=new LinearLayout(activity);list.setOrientation(1);list.setPadding(dp(10),dp(4),dp(10),dp(4));list.setBackgroundColor(0xff252530);
  TextView close=new TextView(activity);close.setText(AppUi.text(activity,"assist_heading"));close.setTextColor(0xffd6d0ee);close.setPadding(0,dp(5),0,dp(5));list.addView(close);close.setOnClickListener(new View.OnClickListener(){public void onClick(View v){generation++;hide();}});
  for(int i=0;i<Math.min(3,rows.length());i++){JSONObject row=rows.getJSONObject(i);final JSONObject value=row.getJSONObject("value");TextView item=new TextView(activity);item.setText(row.getString("name")+"  →  "+value.getString("text").replace('\n',' '));item.setTextColor(0xffeeeeee);item.setTextSize(13);item.setMaxLines(2);item.setPadding(dp(4),dp(8),dp(4),dp(8));list.addView(item);item.setOnClickListener(new View.OnClickListener(){public void onClick(View v){hide();if(!text.equals(editor.getText().toString())||pos!=editor.getSelectionStart()||pos!=editor.getSelectionEnd())return;try{busy=true;EmmetBridge.cancel(activity);int start=value.getInt("start"),end=value.getInt("end");String replacement=value.getString("text");editor.beginBatchEdit();try{editor.getText().replace(start,end,replacement);editor.setSelection(start+value.getInt("selectionStart"),start+value.getInt("selectionEnd"));EmmetFields.start(activity,editor,start,value);}finally{editor.endBatchEdit();}}catch(Exception ex){}finally{busy=false;}}});}
  AppUi.applyFont(list);
  Rect frame=new Rect();editor.getWindowVisibleDisplayFrame(frame);int width=Math.min(frame.width()-dp(20),dp(520));list.measure(View.MeasureSpec.makeMeasureSpec(width,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(dp(220),View.MeasureSpec.AT_MOST));popup=new PopupWindow(list,width,list.getMeasuredHeight(),false);popup.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(0xff252530));popup.setInputMethodMode(PopupWindow.INPUT_METHOD_NEEDED);popup.setElevation(dp(8));popup.showAtLocation(editor,Gravity.TOP|Gravity.LEFT,frame.left+dp(10),Math.max(frame.top,frame.bottom-list.getMeasuredHeight()-dp(8)));
 }
}
